# ============================================================
# ML Aggregator: Hybrid Scoring System
# ============================================================
# Combines the 4 engine outputs into a final verdict score.
#
# TWO MODES:
# 1. ML Mode:       XGBoost trained on historical pipeline
#                    outputs → requires labeled dataset
# 2. Heuristic Mode: Weighted sum of engine scores (no training)
#
# ML Requirement: ★★ MODERATE
#   - Dataset: Tabular (NOT text) — rows of engine features with
#              ground-truth labels (phishing vs. legitimate)
#   - Size:    1K-10K labeled samples recommended
#   - Format:  CSV with 24 numeric features + binary label
#   - Source:  Generated by running the pipeline on labeled emails
#              and recording the engine outputs
# ============================================================

from __future__ import annotations

import os
from typing import Optional

import numpy as np
from loguru import logger

from pipeline.models import (
    HeaderAnalysisResult,
    StructuralAnalysisResult,
    NLPAnalysisResult,
    LinkAnalysisResult,
    AggregatorFeatureVector,
    PipelineVerdict,
    VerdictLabel,
    VerdictAction,
)


class MLAggregator:
    """
    Hybrid ML Aggregator that produces the final phishing verdict.

    ARCHITECTURE:
    ─────────────────────────────────────────────────────────────
    The 4 engines each produce a result object. The aggregator:

    1. EXTRACTS features from all engine results:
       - 4 continuous scores (0-25/30 range)
       - 12 binary detection flags (0 or 1)
       - 5 continuous confidence values (0.0-1.0)
       - 3 cross-engine interaction features
       → Total: 24 features

    2. PREDICTS the final score using either:
       a) A trained XGBoost model (if available)
       b) A weighted heuristic sum (fallback)

    3. MAPS the score to a BINARY verdict (CLEAN or MALICIOUS)

    ML MODEL DETAILS:
    ─────────────────────────────────────────────────────────────
    Type:       XGBoost Classifier
    Input:      24-dimensional feature vector (see AggregatorFeatureVector)
    Output:     Probability of phishing (0.0 to 1.0), scaled to 0-100
    
    TRAINING DATASET REQUIREMENTS:
    ─────────────────────────────────────────────────────────────
    Type:       TABULAR (structured numeric data)
    NOT:        Text data — the NLP model handles text separately
    
    How to generate:
    1. Collect a corpus of labeled emails (phishing + legitimate)
    2. Run each email through the 4-engine pipeline
    3. Record the 24-feature vector + ground-truth label
    4. Train XGBoost on this tabular dataset
    
    Recommended size:
    - Minimum:  1,000 labeled samples (500 phishing + 500 legit)
    - Ideal:    10,000+ samples for robust generalization
    
    Format:     CSV with columns matching AggregatorFeatureVector.feature_names()
                + a 'label' column (1=phishing, 0=legitimate)
    
    Algorithm:  XGBoost
    - XGBoost:  max_depth=6, n_estimators=300, learning_rate=0.05,
                scale_pos_weight=<ratio for class imbalance>
    ─────────────────────────────────────────────────────────────
    """

    def __init__(self, config: Optional[dict] = None):
        self.config = config or {}
        self._model = None
        self._model_type: str = "heuristic"
        self._load_model()

    def _load_model(self) -> None:
        """
        Attempt to load a pre-trained XGBoost model.
        Falls back to heuristic scoring if model is unavailable.
        """
        model_path = self.config.get("model_path", "")

        if not model_path or not os.path.exists(model_path):
            logger.info(
                f"[Aggregator] No trained model found at '{model_path}'. "
                f"Using heuristic scoring."
            )
            self._model_type = "heuristic"
            return

        try:
            self._load_xgboost(model_path)
        except Exception as e:
            logger.warning(
                f"[Aggregator] Failed to load XGBoost model: {e}. "
                f"Falling back to heuristic."
            )
            self._model_type = "heuristic"

    def _load_xgboost(self, model_path: str) -> None:
        """Load a trained XGBoost model from JSON/binary file."""
        import xgboost as xgb

        self._model = xgb.XGBClassifier()
        self._model.load_model(model_path)
        self._model_type = "xgboost"
        logger.info(f"[Aggregator] Loaded XGBoost model from {model_path}")

    # ────────────────────────────────────────────────────────
    # Feature Engineering
    # ────────────────────────────────────────────────────────

    def build_feature_vector(
        self,
        header: HeaderAnalysisResult,
        structure: StructuralAnalysisResult,
        nlp: NLPAnalysisResult,
        links: LinkAnalysisResult,
    ) -> AggregatorFeatureVector:
        """
        Transform engine results into a 30-dimensional feature vector.

        This is the CRITICAL bridge between the rule-based engines
        and the ML model. The feature engineering here determines
        what signals the aggregator can learn from.

        Feature categories:
        ─────────────────────────────────────────────────────
        Raw Scores (4):      Continuous engine scores
        Binary Flags (12):   Boolean detection indicators
        Confidence (5):      NLP model confidence values
        Interactions (3):    Cross-engine feature products
        New Signals (6):     v2 detection features
        ─────────────────────────────────────────────────────
        """
        fv = AggregatorFeatureVector()

        # ── Raw Engine Scores ───────────────────────────────
        fv.header_score = header.score
        fv.structural_score = structure.score
        fv.nlp_score = nlp.score
        fv.link_score = links.score

        # ── Binary Detection Flags ──────────────────────────
        fv.display_name_spoofing = int(header.display_name_spoofing_detected)
        fv.reply_to_mismatch = int(header.reply_to_mismatch_detected)
        fv.xmailer_anomaly = int(header.xmailer_anomaly_detected)
        fv.new_domain = int(header.new_domain_flag)
        fv.typosquatting = int(header.typosquatting_detected)
        fv.hidden_text = int(structure.hidden_text_detected)
        fv.zero_width_chars = int(structure.zero_width_chars_detected)
        fv.image_only = int(structure.image_only_email)

        # ── Cross-Engine Validation: Brand Impersonation ────────
        # Engine 2 flags brand impersonation if it sees a brand logo,
        # but only Aggregator knows if the sender domain legitimately matches!
        if structure.brand_impersonation_detected:
            impersonated = structure.raw_signals.get("impersonated_brand", "")
            actual_domain = header.raw_signals.get("actual_domain", "")
            
            # If the brand name legitimately appears in the sender's domain,
            # it is NOT impersonation, it is the actual brand emailing!
            if impersonated and impersonated in actual_domain:
                fv.brand_impersonation = 0
                fv.structural_score -= structure.brand_impersonation_score
                logger.info(
                    f"[Aggregator] Negating Brand Impersonation: '{impersonated}' "
                    f"is legitimately in sender domain '{actual_domain}'"
                )
            else:
                fv.brand_impersonation = 1
        else:
            fv.brand_impersonation = 0

        fv.href_mismatch = int(links.href_mismatch_detected)
        fv.url_obfuscation = int(links.url_obfuscation_detected)
        fv.homograph_attack = int(links.homograph_attack_detected)

        # ── NLP Confidence Values ───────────────────────────
        fv.nlp_phishing_probability = nlp.phishing_probability
        fv.nlp_intent_confidence = nlp.intent_confidence
        fv.urgency_score = nlp.urgency_coercion_score
        fv.credential_harvesting_score = nlp.credential_harvesting_score
        fv.financial_fraud_score = nlp.financial_fraud_bec_score

        # ── Cross-Engine Interaction Features ───────────────
        fv.header_x_link_risk = header.score * links.score
        fv.nlp_x_structure_risk = nlp.score * structure.score

        # Count total flags triggered (includes new flags)
        fv.total_flags_triggered = sum([
            fv.display_name_spoofing, fv.reply_to_mismatch,
            fv.xmailer_anomaly, fv.new_domain, fv.typosquatting,
            fv.hidden_text, fv.zero_width_chars, fv.image_only,
            fv.brand_impersonation, fv.href_mismatch,
            fv.url_obfuscation, fv.homograph_attack,
        ])

        # ── v2 Detection Features ──────────────────────────
        fv.credential_form_detected = int(structure.credential_form_detected)
        fv.image_wrapped_links = int(links.image_wrapped_link_detected)
        fv.suspicious_tld_count = len(links.suspicious_tlds)
        fv.login_url_pattern = int(links.login_url_pattern_detected)
        fv.oauth_consent_score = nlp.oauth_consent_score
        fv.auth_failure_detected = int(header.auth_failure_detected)

        # Include new flags in total count
        fv.total_flags_triggered += sum([
            fv.credential_form_detected,
            fv.image_wrapped_links,
            fv.login_url_pattern,
            fv.auth_failure_detected,
        ])

        return fv

    # ────────────────────────────────────────────────────────
    # Scoring
    # ────────────────────────────────────────────────────────

    def predict(
        self,
        feature_vector: AggregatorFeatureVector,
    ) -> tuple[float, float]:
        """
        Predict the final phishing score.

        Returns:
            Tuple of (score: 0-100, confidence: 0.0-1.0)

        Uses the trained XGBoost model if available, otherwise
        falls back to weighted heuristic scoring.
        """
        if self._model is not None and self._model_type != "heuristic":
            return self._predict_ml(feature_vector)
        else:
            return self._predict_heuristic(feature_vector)

    def _predict_ml(
        self, fv: AggregatorFeatureVector
    ) -> tuple[float, float]:
        """
        Use the trained XGBoost model for prediction.

        The model outputs P(phishing), which we scale to 0-100.
        """
        try:
            features = np.array([fv.to_feature_array()])

            # Get probability of phishing class
            probabilities = self._model.predict_proba(features)[0]
            phishing_prob = probabilities[1]  # Index 1 = phishing class

            score = phishing_prob * 100.0
            confidence = max(probabilities)  # Confidence = max probability

            logger.info(
                f"[Aggregator] XGBoost prediction: score={score:.1f}, "
                f"confidence={confidence:.3f}"
            )

            return score, confidence

        except Exception as e:
            logger.error(f"XGBoost prediction failed: {e}. Falling back to heuristic.")
            return self._predict_heuristic(fv)

    def _predict_heuristic(
        self, fv: AggregatorFeatureVector
    ) -> tuple[float, float]:
        """
        Weighted heuristic scoring (no ML model required).

        Score = sum of engine scores, scaled to 0-100.
        This matches the architecture's manual weight system:
          Identity (Max 25) + Structure (Max 20) + 
          Links (Max 25) + NLP (Max 30) = Max 100

        Confidence is derived from how many independent engines
        triggered detections (cross-validation principle).
        """
        # Direct sum of engine scores (already weighted by each engine)
        raw_score = (
            fv.header_score
            + fv.structural_score
            + fv.nlp_score
            + fv.link_score
        )

        # Clamp to 0-100
        score = min(max(raw_score, 0.0), 100.0)

        # Confidence: based on engine agreement
        engines_triggered = sum([
            1 if fv.header_score > 0 else 0,
            1 if fv.structural_score > 0 else 0,
            1 if fv.nlp_score > 0 else 0,
            1 if fv.link_score > 0 else 0,
        ])

        # More engines agreeing → higher confidence
        confidence_map = {
            0: 0.10,  # No engines triggered
            1: 0.40,  # Single engine
            2: 0.65,  # Two engines corroborate
            3: 0.85,  # Three engines agree
            4: 0.95,  # All four engines agree
        }
        confidence = confidence_map.get(engines_triggered, 0.5)

        logger.info(
            f"[Aggregator] Heuristic prediction: score={score:.1f}, "
            f"confidence={confidence:.2f}, "
            f"engines_triggered={engines_triggered}/4"
        )

        return score, confidence

    # ────────────────────────────────────────────────────────
    # Verdict Mapping
    # ────────────────────────────────────────────────────────

    def determine_verdict(
        self,
        score: float,
        confidence: float,
        header: HeaderAnalysisResult,
        structure: StructuralAnalysisResult,
        nlp: NLPAnalysisResult,
        links: LinkAnalysisResult,
        feature_vector: AggregatorFeatureVector,
    ) -> PipelineVerdict:
        """
        Map the final score to a BINARY verdict.

        Includes rule-based overrides that catch compound threats
        the ML model may underweight due to training distribution.

        Thresholds:
            0-50:   CLEAN      → Safe delivery
            51-100: MALICIOUS  → Drop + sandbox IoCs
        """
        # ── Rule-Based Override System ───────────────────────
        # These overrides catch OBVIOUS phishing patterns that the
        # XGBoost model may underweight because it over-relies on
        # Engine 1 (Header) scores from the training distribution.
        
        override_reason = None
        adjusted_score = score

        # Override 1: Image-Only + Obfuscated URLs + Image-Wrapped Links
        # This is a classic phishing combo: hide the lure in an image,
        # wrap it in a clickable link, and obfuscate the destination.
        if (structure.image_only_email 
                and links.url_obfuscation_detected
                and links.image_wrapped_link_detected):
            min_score = 72.0
            if adjusted_score < min_score:
                adjusted_score = min_score
                override_reason = (
                    "Image-only email with obfuscated URLs and image-wrapped links "
                    "(classic visual phishing combo)"
                )

        # Override 2: High Link Score (>=20/25) + Image-Only Email
        # Even without obfuscation, image-only + many suspicious links is bad
        if structure.image_only_email and links.score >= 20:
            min_score = 65.0
            if adjusted_score < min_score:
                adjusted_score = min_score
                override_reason = (
                    f"Image-only email with high link risk ({links.score}/25)"
                )

        # Override 3: Max Link Score (25/25) + structural flag + corroboration
        # Only override if there's ADDITIONAL evidence from NLP or Header.
        # Without corroboration, this pattern matches legitimate marketing emails
        # (which have tracking URLs + preheader CSS = high link + structure scores).
        if links.score >= 25 and structure.score >= 10:
            has_nlp_signal = nlp.score > 0 or nlp.phishing_probability > 0.3
            has_header_signal = header.score >= 15
            if has_nlp_signal or has_header_signal:
                min_score = 60.0
                if adjusted_score < min_score:
                    adjusted_score = min_score
                    override_reason = (
                        f"Maximum link risk ({links.score}/25) combined with "
                        f"structural anomalies ({structure.score}/20) and "
                        f"corroborating evidence (NLP={nlp.score}, Header={header.score})"
                    )

        # Override 4: Display Name Spoofing + any link threat
        # If the sender is spoofing a brand AND links are suspicious
        if header.display_name_spoofing_detected and links.score >= 15:
            min_score = 70.0
            if adjusted_score < min_score:
                adjusted_score = min_score
                override_reason = (
                    f"Display name spoofing detected with suspicious links "
                    f"({links.score}/25)"
                )

        # Override 5: 5+ flags triggered but ML says clean
        # Raised from 4 to 5 because legitimate marketing emails commonly
        # trigger 4 flags (subdomain reply-to, preheader CSS, tracking URLs,
        # image banners).
        if feature_vector.total_flags_triggered >= 5 and adjusted_score < 55:
            min_score = 55.0
            adjusted_score = min_score
            override_reason = (
                f"{feature_vector.total_flags_triggered} independent flags triggered "
                f"across multiple engines"
            )

        # Log the override if it was applied
        if override_reason:
            adjusted_confidence = max(0.70, confidence - 0.15)
            logger.warning(
                f"[Aggregator] RULE OVERRIDE: ML score {score:.1f} → {adjusted_score:.1f} | "
                f"Reason: {override_reason}"
            )
            score = adjusted_score
            confidence = adjusted_confidence

        # ── Standard Verdict Mapping ─────────────────────────
        # Binary classification: CLEAN or MALICIOUS
        if score <= 50:
            label = VerdictLabel.CLEAN
            action = VerdictAction.DELIVER
        else:
            label = VerdictLabel.MALICIOUS
            action = VerdictAction.DROP

        # Build verdict
        verdict = PipelineVerdict(
            final_score=round(score, 2),
            label=label,
            action=action,
            confidence=round(confidence, 4),
            header_result=header,
            structural_result=structure,
            nlp_result=nlp,
            link_result=links,
            feature_vector=feature_vector,
            aggregator_used=self._model_type,
            # Actionable flags — only triggered for MALICIOUS
            route_to_sandbox=(label == VerdictLabel.MALICIOUS),
            extract_iocs=(label == VerdictLabel.MALICIOUS),
        )

        return verdict

    # ────────────────────────────────────────────────────────
    # Training Utilities
    # ────────────────────────────────────────────────────────

    @staticmethod
    def train_xgboost(
        training_data_path: str,
        output_model_path: str,
        hyperparams: Optional[dict] = None,
    ) -> dict:
        """
        Train an XGBoost aggregator model on historical pipeline outputs.

        DATASET FORMAT (CSV):
        ─────────────────────────────────────────────────────
        header_score,structural_score,nlp_score,...,label
        15.0,10.0,24.0,...,1
        0.0,0.0,3.0,...,0
        ─────────────────────────────────────────────────────

        Columns: All 24 features from AggregatorFeatureVector.feature_names()
                 + 'label' column (1=phishing, 0=legitimate)

        Args:
            training_data_path: Path to CSV training data.
            output_model_path:  Path to save trained model.
            hyperparams:        Optional XGBoost hyperparameters.

        Returns:
            Dictionary with training metrics (accuracy, F1, etc.)
        """
        import pandas as pd
        import xgboost as xgb
        from sklearn.model_selection import train_test_split
        from sklearn.metrics import (
            classification_report,
            f1_score,
            precision_score,
            recall_score,
        )

        # Load dataset
        df = pd.read_csv(training_data_path)
        feature_names = AggregatorFeatureVector.feature_names()

        X = df[feature_names].values
        y = df["label"].values

        # Split: 80% train, 20% test
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42, stratify=y
        )

        # Handle class imbalance
        n_positive = sum(y_train == 1)
        n_negative = sum(y_train == 0)
        scale_pos_weight = n_negative / n_positive if n_positive > 0 else 1.0

        # Default hyperparameters (optimized for cybersecurity)
        default_params = {
            "max_depth": 6,
            "n_estimators": 300,
            "learning_rate": 0.05,
            "scale_pos_weight": scale_pos_weight,
            "eval_metric": "logloss",
            "use_label_encoder": False,
            "random_state": 42,
            "subsample": 0.8,
            "colsample_bytree": 0.8,
            "reg_alpha": 0.1,  # L1 regularization
            "reg_lambda": 1.0,  # L2 regularization
        }

        params = {**default_params, **(hyperparams or {})}

        # Train
        model = xgb.XGBClassifier(**params)
        model.fit(
            X_train,
            y_train,
            eval_set=[(X_test, y_test)],
            verbose=True,
        )

        # Evaluate
        y_pred = model.predict(X_test)
        metrics = {
            "accuracy": float((y_pred == y_test).mean()),
            "f1": float(f1_score(y_test, y_pred)),
            "precision": float(precision_score(y_test, y_pred)),
            "recall": float(recall_score(y_test, y_pred)),
            "classification_report": classification_report(y_test, y_pred),
        }

        # Feature importance
        importance = dict(zip(feature_names, model.feature_importances_))
        metrics["feature_importance"] = dict(
            sorted(importance.items(), key=lambda x: x[1], reverse=True)
        )

        # Save model
        model.save_model(output_model_path)
        logger.info(
            f"[Aggregator] XGBoost model saved to {output_model_path}"
        )
        logger.info(f"[Aggregator] Metrics: {metrics}")

        return metrics
