# ============================================================
# ML Aggregator Training Script — XGBoost Only
# ============================================================
# Trains the XGBoost aggregator model on tabular feature data
# generated by running the pipeline on a labeled email corpus.
#
# Dataset Format (CSV):
#   header_score,structural_score,...,total_flags_triggered,label
#   15.0,10.0,...,5,1
#   0.0,0.0,...,0,0
#
# Usage:
#   python training/train_aggregator.py \
#       --data_path data/aggregator_training.csv \
#       --output_path models/aggregator_xgb.json
# ============================================================

from __future__ import annotations

import argparse
import sys
import os

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from loguru import logger
from pipeline.aggregator import MLAggregator


def main():
    parser = argparse.ArgumentParser(
        description="Train the XGBoost Aggregator model"
    )
    parser.add_argument(
        "--data_path",
        type=str,
        required=True,
        help="Path to CSV training data (24 features + label column)",
    )
    parser.add_argument(
        "--output_path",
        type=str,
        default="models/aggregator_xgb.json",
        help="Path to save trained XGBoost model",
    )

    args = parser.parse_args()

    logger.info("Training XGBoost aggregator model")
    logger.info(f"Data: {args.data_path}")
    logger.info(f"Output: {args.output_path}")

    # Create output directory
    os.makedirs(os.path.dirname(args.output_path), exist_ok=True)

    metrics = MLAggregator.train_xgboost(
        training_data_path=args.data_path,
        output_model_path=args.output_path,
    )

    logger.info(f"\nTraining complete!")
    logger.info(f"Accuracy: {metrics['accuracy']:.4f}")
    logger.info(f"F1 Score: {metrics['f1']:.4f}")
    logger.info(f"Precision: {metrics['precision']:.4f}")
    logger.info(f"Recall: {metrics['recall']:.4f}")

    logger.info(f"\nTop 10 Feature Importances:")
    for i, (feature, importance) in enumerate(
        list(metrics["feature_importance"].items())[:10], 1
    ):
        logger.info(f"  {i}. {feature}: {importance:.4f}")


if __name__ == "__main__":
    main()
